// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wirxabhllquwommibqey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcnhhYmhsbHF1d29tbWlicWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTM1MzksImV4cCI6MjA2NTU2OTUzOX0.KqhlXBer9RlTnhGxThcRz4gvM1tl4SGii54ZoPjmSsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);